core/urls.py
from django.urls import path

from core.views import MenuView

app_name = "core"
urlpatterns = [
    path("<uuid:codigo>/", MenuView.as_view(), name="menu-detail"),
]

gestion/urls.py
from django.urls import path

from gestion.views import (
    CategoriaCreateView,
    CategoriaDeleteView,
    CategoriaEditView,
    DashboardView,
    MenuCreateView,
    MenuDeleteView,
    MenuEditView,
    MenuPrintQrView,
    OcultarCategoriaView,
    OcultarMenuView,
    PlatoCreateView,
    PlatoDeleteView,
    PlatoEditView,
    PublicarCategoriaView,
    PublicarMenuView,
)

app_name = "gestion"
urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("crear-menu/", MenuCreateView.as_view(), name="crear-menu"),
    path("editar-menu/<int:pk>/", MenuEditView.as_view(), name="editar-menu"),
    path(
        "editar-menu/<int:pk>/crear-categoria/",
        CategoriaCreateView.as_view(),
        name="crear-categoria",
    ),
    path("eliminar-menu/<int:pk>/", MenuDeleteView.as_view(), name="eliminar-menu"),
    path(
        "categoria/<int:pk>/",
        CategoriaEditView.as_view(),
        name="editar-categoria",
    ),
    path(
        "editar-categoria/<int:pk>/crear-plato/",
        PlatoCreateView.as_view(),
        name="crear-plato",
    ),
    path(
        "eliminar-categoria/<int:pk>/",
        CategoriaDeleteView.as_view(),
        name="eliminar-categoria",
    ),
    path(
        "plato/<int:pk>/",
        PlatoEditView.as_view(),
        name="editar-plato",
    ),
    path("eliminar-plato/<int:pk>/", PlatoDeleteView.as_view(), name="eliminar-plato"),
    path("menu/<int:pk>/qr/", MenuPrintQrView.as_view(), name="generar-qr"),
    path("menu/<int:pk>/publicar/", PublicarMenuView.as_view(), name="publicar-menu"),
    path("menu/<int:pk>/ocultar/", OcultarMenuView.as_view(), name="ocultar-menu"),
    path(
        "<int:pk>/publicar/", PublicarCategoriaView.as_view(), name="publicar-categoria"
    ),
    path("<int:pk>/ocultar/", OcultarCategoriaView.as_view(), name="ocultar-categoria"),
]

qrmenu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("cuentas/", include("cuentas.urls")),
    # path("cuentas/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="landing.html"), name="landing"),
    path("menus/", include("core.urls")),
    path("panel/", include("gestion.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from uuid import uuid4

from django.conf import settings
from django.db import models


class BaseModel(models.Model):
    creado = models.DateTimeField("Fecha creada", auto_now_add=True)
    modificado = models.DateTimeField("Fecha modificada", auto_now=True)

    class Meta:
        abstract = True


class Menu(BaseModel):
    codigo = models.UUIDField("Codigo", default=uuid4, null=False)
    nombre = models.CharField("Nombre", max_length=50)
    descripcion = models.TextField("Descripción")
    estado = models.CharField(
        "Estado",
        max_length=100,
        default="oculto",
        choices=[("publicado", "Publicado"), ("oculto", "Oculto")],
    )
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="usuario", on_delete=models.PROTECT
    )

    def __str__(self):
        return self.nombre


class Categoria(BaseModel):
    nombre = models.CharField("Nombre", max_length=50)
    descripcion = models.TextField("Descripción")
    estado = models.CharField(
        "Estado",
        max_length=100,
        default="oculta",
        choices=[("publicada", "Publicada"), ("oculta", "Oculta")],
    )
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Plato(BaseModel):
    nombre = models.CharField("Nombre", max_length=100)
    precio = models.DecimalField("Precio", decimal_places=2, max_digits=8)
    descripcion = models.TextField("Descripción")
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField("Imagen", null=True)

    def __str__(self):
        return self.nombre


# Analytics
class Acceso(BaseModel):
    user_agent = models.CharField("User Agent", max_length=200)
    ip = models.CharField("IP", max_length=200)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)

    def __str__(self):
        return self.id

gestion/forms.py
from django import forms
from django.conf import settings

from core import models


# Menú section
class MenuCreateForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ["nombre", "descripcion"]

    def __init__(self, *args, user, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        return models.Menu.objects.create(
            nombre=self.cleaned_data["nombre"],
            descripcion=self.cleaned_data["descripcion"],
            usuario=self.user,
        )

    def clean(self):
        cleaned_data = super().clean()
        menus = models.Menu.objects.filter(usuario=self.user).count()

        if menus >= settings.MAX_MENUS and not self.user.is_superuser:
            raise forms.ValidationError("Has alcanzado el límite de menús")

        return cleaned_data


class MenuUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ["nombre", "descripcion"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["descripcion"].widget = forms.Textarea()


# Categories section
class CategoriaCreateForm(forms.ModelForm):
    class Meta:
        model = models.Categoria
        fields = ["nombre", "descripcion"]

    def __init__(self, *args, menu, **kwargs):
        self.menu = menu
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        return models.Categoria.objects.create(
            nombre=self.cleaned_data["nombre"],
            descripcion=self.cleaned_data["descripcion"],
            menu=self.menu,
        )


class CategoriaUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Categoria
        fields = ["nombre", "descripcion"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


# Plates section
class PlatoCreateForm(forms.ModelForm):
    class Meta:
        model = models.Plato
        fields = ["nombre", "descripcion", "precio"]
        widgets = {"precio": forms.NumberInput(attrs={"min": 0})}

    def __init__(self, *args, categoria, **kwargs):
        self.categoria = categoria
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        return models.Plato.objects.create(
            nombre=self.cleaned_data["nombre"],
            descripcion=self.cleaned_data["descripcion"],
            precio=self.cleaned_data["precio"],
            categoria=self.categoria,
        )


class PlatoUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Plato
        fields = ["nombre", "descripcion", "precio"]
        widgets = {"precio": forms.NumberInput(attrs={"min": 0})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

gestion/views.py
from io import BytesIO

import qrcode
from django import forms
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from core import models
from gestion import forms as gestion_forms
from gestion import mixins


# Dashboard del usuario
class DashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = "gestion/dashboard.html"
    login_url = reverse_lazy("login")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["menus"] = models.Menu.objects.filter(usuario=self.request.user).annotate(
            plato_count=Count("categoria__plato"),
            acceso_count=Count("acceso", distinct=True),
        )
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": True,
            }
        ]
        data["max_menus"] = settings.MAX_MENUS
        return data


# Menus section
class MenuCreateView(mixins.MessageMixin, LoginRequiredMixin, CreateView):
    form_class = gestion_forms.MenuCreateForm
    template_name = "gestion/crear_menu.html"
    success_url = reverse_lazy("gestion:dashboard")
    login_url = reverse_lazy("login")
    msg_desc = "Menú creado con éxito"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": "Crear Menú",
                "href": reverse_lazy("gestion:crear-menu"),
                "active": True,
            },
        ]
        return context


class MenuUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ["nombre", "descripcion"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["descripcion"].widget = forms.Textarea()


class MenuEditView(mixins.MessageMixin, LoginRequiredMixin, UpdateView):
    model = models.Menu
    form_class = gestion_forms.MenuUpdateForm
    template_name = "gestion/editar_menu.html"
    login_url = reverse_lazy("login")
    msg_desc = "Menú editado con éxito"

    def get_queryset(self):
        return models.Menu.objects.filter(usuario=self.request.user)

    def get_success_url(self):
        return reverse_lazy("gestion:editar-menu", args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": self.get_object().nombre,
                "href": reverse_lazy(
                    "gestion:editar-menu", args=[self.get_object().pk]
                ),  # noqa: E501
                "active": True,
            },
        ]
        return data


class MenuDeleteView(mixins.MessageMixin, LoginRequiredMixin, DeleteView):
    model = models.Menu
    success_url = reverse_lazy("gestion:dashboard")
    msg_desc = "Menú eliminado con éxito"

    def get_queryset(self):
        return models.Menu.objects.filter(usuario=self.request.user)


# Categories section
class CategoriaCreateView(mixins.MessageMixin, LoginRequiredMixin, UpdateView):
    model = models.Menu
    form_class = gestion_forms.CategoriaCreateForm
    template_name = "gestion/crear_categoria.html"
    login_url = reverse_lazy("login")
    msg_desc = "Categoría creada con éxito"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = models.Categoria()
        kwargs["menu"] = self.get_object()
        return kwargs

    def get_queryset(self):
        return models.Menu.objects.filter(usuario=self.request.user)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["menu"] = self.get_object()
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": self.get_object().nombre,
                "href": reverse_lazy(
                    "gestion:editar-menu", args=[self.get_object().pk]
                ),
                "active": False,
            },
            {
                "label": "Crear categoría",
                "href": reverse_lazy(
                    "gestion:crear-categoria", args=[self.get_object().pk]
                ),
                "active": True,
            },
        ]
        return data

    def get_success_url(self):
        return reverse_lazy("gestion:editar-menu", args=[self.get_object().pk])


class CategoriaEditView(mixins.MessageMixin, LoginRequiredMixin, UpdateView):
    model = models.Categoria
    form_class = gestion_forms.CategoriaUpdateForm
    template_name = "gestion/editar_categoria.html"
    login_url = reverse_lazy("login")
    msg_desc = "Categoría editada con éxito"

    def get_queryset(self):
        return models.Categoria.objects.filter(
            menu__usuario=self.request.user
        ).select_related("menu__usuario")

    def get_success_url(self):
        return reverse_lazy("gestion:editar-categoria", args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": self.get_object().menu.nombre,
                "href": reverse_lazy(
                    "gestion:editar-menu", args=[self.get_object().menu.pk]
                ),
                "active": False,
            },
            {
                "label": self.get_object().nombre,
                "href": reverse_lazy(
                    "gestion:editar-categoria", args=[self.get_object().pk]
                ),
                "active": True,
            },
        ]
        return data


class CategoriaDeleteView(mixins.MessageMixin, LoginRequiredMixin, DeleteView):
    model = models.Categoria
    msg_desc = "Categoría eliminada con éxito"

    def get_queryset(self):
        return models.Categoria.objects.filter(menu__usuario=self.request.user)

    def get_success_url(self):
        return reverse_lazy("gestion:editar-menu", args=[self.object.menu.pk])


# Plates section
class PlatoCreateView(mixins.MessageMixin, LoginRequiredMixin, UpdateView):
    model = models.Categoria
    form_class = gestion_forms.PlatoCreateForm
    template_name = "gestion/crear_plato.html"
    login_url = reverse_lazy("login")
    msg_desc = "Plato creado con éxito"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = models.Plato()
        kwargs["categoria"] = self.get_object()
        return kwargs

    def get_queryset(self):
        return models.Categoria.objects.filter(
            menu__usuario=self.request.user
        ).select_related("menu__usuario")

    def get_success_url(self):
        return reverse_lazy("gestion:editar-categoria", args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": self.get_object().menu.nombre,
                "href": reverse_lazy(
                    "gestion:editar-menu", args=[self.get_object().pk]
                ),
                "active": False,
            },
            {
                "label": self.get_object().nombre,
                "href": reverse_lazy(
                    "gestion:editar-categoria", args=[self.get_object().pk]
                ),
                "active": False,
            },
            {
                "label": "Crear plato",
                "href": reverse_lazy(
                    "gestion:editar-categoria", args=[self.get_object().pk]
                ),
                "active": False,
            },
        ]
        return data


class PlatoEditView(mixins.MessageMixin, LoginRequiredMixin, UpdateView):
    model = models.Plato
    form_class = gestion_forms.PlatoUpdateForm
    template_name = "gestion/editar_plato.html"
    login_url = reverse_lazy("login")
    msg_desc = "Plato editado con éxito"

    def get_queryset(self):
        return models.Plato.objects.filter(
            categoria__menu__usuario=self.request.user
        ).select_related("categoria__menu__usuario")

    def get_success_url(self):
        return reverse_lazy("gestion:editar-categoria", args=[self.object.categoria.pk])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["breadcrumbs"] = [
            {
                "label": "Panel",
                "href": reverse_lazy("gestion:dashboard"),
                "active": False,
            },
            {
                "label": self.get_object().categoria.menu.nombre,
                "href": reverse_lazy(
                    "gestion:editar-menu", args=[self.get_object().categoria.menu.pk]
                ),

gestion/templates/gestion/crear_plato.html
{% extends 'dashboard_skeleton.html' %}

{% block main_class %}create-menu-page{% endblock %}
{% block title %}Crear Plato | Menudiño{% endblock %}

{% block content %}
    <div class="container is-centered">
        <div class="card is-action-card">
            <div class="card-header has-text-centered">
                <h4 class="card-header-title title is-4">Crear plato</h4>
            </div>
            <form method="POST" action="{% url 'gestion:crear-plato' categoria.pk %}" class="create-menu-form">
                {% csrf_token %}
                <div class="card-content">
                    {% for field in form.visible_fields %}
                        {% include "partials/field.html" with field=field %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="has-text-danger has-text-centered mb-3">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <a href="{% url 'gestion:editar-categoria' categoria.pk%}" class="button">Cancelar</a>
                    <button type="submit" class="button is-primary">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

gestion/templates/gestion/dashboard.html
{% extends 'dashboard_skeleton.html' %}

{% block content %}
  <div  class="mt-6" x-cloak x-data="{ deleteURL: '' }">
    <div class="is-flex is-justify-content-space-between px-3">
      <h3 class="title">Menús</h3>
    </div>
    <section data-el="menu-cards">
      <div class="columns is-multiline m-0" id="grid">
        {% for menu in menus %}
          <div class="column is-6 is-4-widescreen is-flex">
            <div class="card is-entity">
              <div class="card-header">
                <div class="actual-status">
                  {% if menu.estado == "publicado" %}
                    <div class="entity-public"></div>
                  {% else %}
                    <div class="entity-hidden"></div>
                  {% endif %}
                </div>
                <h4 class="card-header-title title is-4">{{ menu.nombre }}</h4>
              </div>
              <div class="card-content">
                {{ menu.descripcion }}
              </div>
              <div class="card-footer is-flex is-flex-direction-column">
                <div class="actions-container">
                  {% if menu.estado == "publicado" %}
                    <a class="card-footer-item" href="{% url 'core:menu-detail' menu.codigo %}" target="_blank">
                      <ion-icon name="eye-outline" title="Previsualizar menú"></ion-icon>
                    </a>
                  {% endif %}
                  <a class="card-footer-item" href="{% url 'gestion:editar-menu' menu.pk %}">
                    <ion-icon name="create-outline" title="Editar menú"></ion-icon>
                  </a>
                  <a class="card-footer-item" x-on:click="deleteURL = '{% url 'gestion:eliminar-menu' menu.pk %}'">
                    <ion-icon name="trash-outline" title="Eliminar menú"></ion-icon>
                  </a>
                  <a class="card-footer-item" href="{% url 'gestion:generar-qr' menu.pk %}">
                    <ion-icon name="qr-code-outline" title="Descargar QR"></ion-icon>
                  </a>
                </div>
                <div class="status-container is-flex is-justify-content-center mt-2">
                  {% if menu.estado == "publicado" %}
                    <form method="POST" action="{% url 'gestion:ocultar-menu' menu.pk %}">
                      {% csrf_token %}
                      <button type="submit" class="button is-danger">Ocultar</button>
                    </form>
                  {% else %}
                    <form method="POST" action="{% url 'gestion:publicar-menu' menu.pk %}">
                      {% csrf_token %}
                      <button type="submit" class="button is-success has-text-white">Publicar</button>
                    </form>
                  {% endif %}
                </div>
              </div>
            </div>
            <div
              x-show="deleteURL"
              class="delete-entity-container"
              x-on:keyup.window.escape="deleteURL = ''"
              >
              <form
                class="delete-entity-form"
                method="POST"
                x-bind:action="deleteURL"
                >
                  {% csrf_token %}
                  <p>Seguro que quieres eliminar el menú?</p>
                  <input
                    x-on:click="deleteURL = ''"
                    type="button"
                    value="Cancelar"
                    class="button"
                  />
                <input type="submit" value="Confirmar" class="button is-primary" />
              </form>
            </div>
          </div>
        {% endfor %}
        {% if menus|length <= max_menus %}
          <div class="column is-6 is-4-widescreen is-flex">
            <a class="card is-entity add-entity-card" href="{% url 'gestion:crear-menu' %}">
              <span>+</span>
            </a>
          </div>
        {% endif%}
      </div>
    </section>
  </div>
{% endblock %}

gestion/templates/gestion/editar_categoria.html
{% extends 'dashboard_skeleton.html' %}

{% block main_class %}create-menu-page{% endblock %}
{% block title %}Editar Categoría - Menudiño{% endblock %}

{% block content %}
  <div class="edit-entity">
    <div data-el="edit-category-card" class="card is-action-card">
      <div class="card-header has-text-centered">
        <h4 class="card-header-title title is-4">Editar Categoría</h4>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="card-content">
          {% for field in form.visible_fields %}
            {% include "partials/field.html" with field=field %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="has-text-danger has-text-centered mb-3">{{ error }}</div>
          {% endfor %}
        </div>
        <div class="card-footer is-flex is-justify-content-center">
          <button type="submit" class="button is-primary">Guardar</button>
        </div>
      </form>
    </div>
    <section 
      x-cloak x-data="{ deleteURL: '' }" 
      class="section table-section is-flex is-flex-direction-column is-align-items-center is-flex-grow-2 has-background-white b-radius"
      data-el="categories-container"
      >
        <div class="table-header is-flex is-justify-content-space-between is-flex-wrap-wrap">
          <h3 class="title">Platos</h3>
          <div class="edit-buttons-container">
            <a class="button" href="{% url 'gestion:dashboard' %}">Volver al panel</a>
            <a class="button is-primary" href="{% url 'gestion:crear-plato' categoria.pk %}">Crear plato</a>
          </div>
        </div>
        <div class="table-container">
          {% if object.plato_set.count > 0 %}
            <table class="table is-stripped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th class="has-text-right">Precio</th>
                        <th></th>
                    </tr>
                </thead>
              <tbody>
                {% for plato in object.plato_set.all %}
                  <tr>
                    <td>{{ plato.nombre }}</td>
                    <td>{{ plato.descripcion }}</td>
                    <td class="has-text-right">{{ plato.precio|floatformat:"2g" }} €</td>
                    <td>
                      <div class="actions-td">
                        <a href="{% url 'gestion:editar-plato' plato.pk %}">
                          <ion-icon name="create-outline" title="Editar menú"></ion-icon>
                        </a>
                        <a x-on:click="deleteURL = '{% url 'gestion:eliminar-plato' plato.pk %}'">
                          <ion-icon name="trash-outline" title="Eliminar menú"></ion-icon>
                        </a>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <div x-show="deleteURL" class="delete-entity-container" x-on:keyup.window.escape="deleteURL = ''">
              <form
                  class="delete-entity-form"
                  method="POST"
                  x-bind:action="deleteURL"
                  x-on:click.outside="deleteURL = ''"
                >
                  {% csrf_token %}
                  <p>Seguro que quieres eliminar el plato?</p>
                  <input x-on:click="deleteURL = ''" type="button" value="Cancelar" class="button" />
                  <input type="submit" value="Confirmar" class="button is-primary" />
              </form>
            </div>
          {% else %}
            <h2 class="title is-5">Aún no has creado ningún plato</h2>
          {% endif %}
        </div>
    </section>
  </div>

{% endblock %}

gestion/templates/gestion/editar_menu.html
{% extends 'dashboard_skeleton.html' %}

{% block main_class %}categories-page{% endblock %}
{% block title %}Editar Menú - Menudiño{% endblock %}

{% block content %}
  <div class="edit-entity">
    <div data-el="edit-menu-card" class="card is-action-card">
      <div class="card-header has-text-centered">
        <h4 class="card-header-title title is-4">Editar Menú</h4>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="card-content">
          {% for field in form.visible_fields %}
            {% include "partials/field.html" with field=field %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="has-text-danger has-text-centered mb-3">{{ error }}</div>
          {% endfor %}
        </div>
        <div class="card-footer is-flex is-justify-content-center">
          <button type="submit" class="button is-primary">Guardar</button>
        </div>
      </form>
    </div>
    <section 
      x-cloak x-data="{ deleteURL: '' }" 
      class="section table-section is-flex is-flex-direction-column is-align-items-center is-flex-grow-2 has-background-white b-radius"
      data-el="categories-container"
      >
      <div class="table-header is-flex is-justify-content-space-between is-flex-wrap-wrap">
        <h3 class="title">Categorías</h3>
        <div class="edit-buttons-container">
          <a class="button" href="{% url 'gestion:dashboard' %}">Volver al panel</a>
          <a class="button is-primary" href="{% url 'gestion:crear-categoria' menu.pk %}">Crear categoría</a>
        </div>
      </div>
      <div class="table-container">
        {% if object.categoria_set.count > 0 %}
          <table class="table is-stripped">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for categoria in object.categoria_set.all %}
                <tr>
                  <td>{{ categoria.nombre }}</td>
                  <td>{{ categoria.descripcion }}</td>
                  {% if categoria.estado == "oculta" %}
                    <td>
                      <form method="POST" action="{% url 'gestion:publicar-categoria' categoria.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="button is-success has-text-white">Publicar</button>
                      </form>
                    </td>
                  {% else %}
                    <td>
                    <form method="POST" action="{% url 'gestion:ocultar-categoria' categoria.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="button is-danger">Ocultar</button>
                      </form>
                    </td>
                  {% endif %}
                  <td>
                    <div class="actions-td">
                      <a href="{% url 'gestion:editar-categoria' categoria.pk %}">
                        <ion-icon name="create-outline" title="Editar menú"></ion-icon>
                      </a>
                      <a x-on:click="deleteURL = '{% url 'gestion:eliminar-categoria' categoria.pk %}'">
                        <ion-icon name="trash-outline" title="Eliminar menú"></ion-icon>
                      </a>
                    </div>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <div x-show="deleteURL" class="delete-entity-container" x-on:keyup.window.escape="deleteURL = ''">
            <form
                class="delete-entity-form"
                method="POST"
                x-bind:action="deleteURL"
                x-on:click.outside="deleteURL = ''"
              >
              {% csrf_token %}
              <p>Seguro que quieres eliminar la categoría?</p>
              <input x-on:click="deleteURL = ''" type="button" value="Cancelar" class="button" />
              <input type="submit" value="Confirmar" class="button is-primary" />
            </form>
          </div>
        {% else %}
            <h2 class="title is-5">Aún no has creado ninguna categoría</h2>
        {% endif %}
      </div>
    </section>
  </div>

{% endblock %}