core/urls.py
from django.urls import path

from core.views import MenuView

app_name = "core"
urlpatterns = [
    path("<uuid:codigo>/", MenuView.as_view(), name="menu-detail"),
]

gestion/urls.py
from django.urls import path

from gestion.views import (
    CategoriaCreateView,
    CategoriaDeleteView,
    CategoriaEditView,
    DashboardView,
    MenuCreateView,
    MenuDeleteView,
    MenuEditView,
    MenuPrintQrView,
    OcultarCategoriaView,
    OcultarMenuView,
    PlatoCreateView,
    PlatoDeleteView,
    PlatoEditView,
    PublicarCategoriaView,
    PublicarMenuView,
)

app_name = "gestion"
urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("crear-menu/", MenuCreateView.as_view(), name="crear-menu"),
    path("editar-menu/<int:pk>/", MenuEditView.as_view(), name="editar-menu"),
    path(
        "editar-menu/<int:pk>/crear-categoria/",
        CategoriaCreateView.as_view(),
        name="crear-categoria",
    ),
    path("eliminar-menu/<int:pk>/", MenuDeleteView.as_view(), name="eliminar-menu"),
    path(
        "categoria/<int:pk>/",
        CategoriaEditView.as_view(),
        name="editar-categoria",
    ),
    path(
        "editar-categoria/<int:pk>/crear-plato/",
        PlatoCreateView.as_view(),
        name="crear-plato",
    ),
    path(
        "eliminar-categoria/<int:pk>/",
        CategoriaDeleteView.as_view(),
        name="eliminar-categoria",
    ),
    path(
        "plato/<int:pk>/",
        PlatoEditView.as_view(),
        name="editar-plato",
    ),
    path("eliminar-plato/<int:pk>/", PlatoDeleteView.as_view(), name="eliminar-plato"),
    path("menu/<int:pk>/qr/", MenuPrintQrView.as_view(), name="generar-qr"),
    path("menu/<int:pk>/publicar/", PublicarMenuView.as_view(), name="publicar-menu"),
    path("menu/<int:pk>/ocultar/", OcultarMenuView.as_view(), name="ocultar-menu"),
    path(
        "<int:pk>/publicar/", PublicarCategoriaView.as_view(), name="publicar-categoria"
    ),
    path("<int:pk>/ocultar/", OcultarCategoriaView.as_view(), name="ocultar-categoria"),
]

qrmenu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("cuentas/", include("cuentas.urls")),
    # path("cuentas/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="landing.html"), name="landing"),
    path("menus/", include("core.urls")),
    path("panel/", include("gestion.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Marcos Rodrigues González" />
        <meta name="copyright" content="Marcos Rodrigues González" />
        <meta name="robots" content="noindex"/>
        <title>{% block title %}{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&display=swap" rel="stylesheet">
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'normalize.css' %}"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'dist/accounts.css' %}"
        />
        {# Favicon #}
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#383838">
        <meta name="apple-mobile-web-app-title" content="Menudi&ntilde;o">
        <meta name="application-name" content="Menudi&ntilde;o">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="theme-color" content="#ffffff">
    </head>
    <body>
        <main class="{% block main_class %}{% endblock %}">
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

templates/dashboard_skeleton.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Marcos Rodrigues González" />
    <meta name="copyright" content="Marcos Rodrigues González" />
    <meta name="robots" content="noindex"/>
    <title>{% block title %}Gestión - Menudiño{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'normalize.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'normalize.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'dist/dashboard.css' %}"
    />
    <script src="//unpkg.com/alpinejs" defer></script>
    {% comment %} Favicon {% endcomment %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#383838">
    <meta name="apple-mobile-web-app-title" content="Menudi&ntilde;o">
    <meta name="application-name" content="Menudi&ntilde;o">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <div class="dashboard-container has-background-light">
      <header>
        <nav class="navbar is-primary">
          <div class="container is-flex is-justify-content-space-evenly is-align-items-center">
            <div class="navbar-brand is-flex-grow-1">
              <a class="navbar-item is-primary" href="{% url "gestion:dashboard" %}">
                <strong>{{ request.user }}</strong>
              </a>
            </div>
            <div class="navbar-end is-flex">
              <div class="navbar-item">
                {% if user.is_authenticated %}
                  <a class="has-text-white is-underlined" href="{% url 'logout' %}">
                    Cerrar Sesión
                  </a>
                {% else %}
                  <div class="buttons">
                    <button class="button is-primary" href="{% url 'registrarse' %}">
                      Crear Cuenta
                    </button>
                    <button class="button is-primary" href="{% url 'login' %}">
                      Iniciar Sesión
                    </button>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
        <nav class="breadcrumb mb-4" aria-label="breadcrumbs" style="overflow: auto;">
          <div class="container px-3 py-2 has-background-white">
            <ul style="flex-wrap: nowrap !important;">
              {% for breadcrumb in breadcrumbs %}
                <li class="{% if breadcrumb.active %}is-active{% endif %}">
                  <a href="{{ breadcrumb.href }}">{{ breadcrumb.label }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </nav>
      </header>
      <main class="{% block main_class %}{% endblock %}">
        {% if messages %}
          <div class="px-5">
            {% for message in messages %}
              <div class="container">
                <div
                  x-cloak
                  x-data="{ show: true }"
                  x-show="show"
                  x-transition
                  class="notification {{ message.tags }} is-light"
                >
                  <button x-on:click="show = false" class="delete" aria-label="delete"></button>
                  {{ message }}
                </div>
              </div>
            {% endfor %}
          </div>
        {% endif %}
        <div class="container b-radius">
          {% block content %}
          {% endblock %}
        </div>
      </main>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </body>
</html>

templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta
            name="description"
            content="Menudiño. Genera tu menú adaptado a tus necesidades, con opción a descargar un qr con acceso directo a tu menú"/>
        <meta name="keywords" content="menú, carta, qr, pdf, generador, restaurante, bar, cafetería"/>
        <meta name="author" content="Marcos Rodrigues González" />
        <meta name="copyright" content="Marcos Rodrigues González" />
        <meta name="robots" content="index,nofollow"/>
        <title>Menudiño | Generación de Menús</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700;800;900&display=swap" rel="stylesheet">
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'normalize.css' %}"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'dist/landing.css' %}"
        />
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#383838">
        <meta name="apple-mobile-web-app-title" content="Menudi&ntilde;o">
        <meta name="application-name" content="Menudi&ntilde;o">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="theme-color" content="#ffffff">
    </head>
    <body>
        <nav class="navbar">
            <div id="landing-container" class="container is-flex is-align-items-center is-justify-content-space-between p-3">
                <div class="navbar-brand">
                    <img src="/static/images/landing/Menudiño - Logo.png"/>
                </div>
                <hr>
                <div class="navbar-end">
                    <div>
                        <a class="has-text-black" href="{% url 'registrarse' %}">
                            <strong>Registrarse</strong>
                        </a>
                        <span> | </span>
                        <a class="has-text-black has-text-weight-light" href="{% url 'login' %}">
                            Iniciar Sesión
                        </a>
                    </div>
                </div>
            </div>
        </nav>
        <header class="columns is-marginless has-text-white p-5 ">
            <div class="container columns">
                <div class="column" id="header-left-col">
                    <h2 class="is-size-3-desktop hast-text-white mb-6 has-text-weight-bold">
                        Gestión integral de carta digital para tu negocio
                    </h2>
                    <ul>
                        <li class="list-item pb-2">Múltiples temas adaptados a dispositivos móviles</li>
                        <li class="list-item pb-2">Genera QR’s para facilitar el acceso a tus clientes</li>
                        <li class="list-item pb-2">Siempre online y disponible para editar</li>
                        <li class="list-item">Actívalo o desactívalo con un click</li>
                    </ul>
                </div>
                <div class="column has-text-centered">
                    <img src="{% static 'images/landing/header-img.png' %}"/>
                </div>
            </div>
        </header>
        <section class="section py-4 pb-6 has-background-white">
            <div class="container">
                <h2 class="is-size-4 has-text-centered has-text-black has-text-weight-bold my-4">
                    Planes
                </h2>
                <div class="columns">
                    <div class="column is-marginless">
                        <div class="card free-card">
                            <div class="card-content">
                                <h3 class="has-text-centered is-size-4 has-text-weight-bold mb-3">Gratuito</h3>
                                <ul class="has-text-black">
                                    <li class="list-item mb-2">Hasta 5 menús</li>
                                    <li class="list-item">Generación de código QR</li>
                                </ul>
                            </div>
                            <div class="card-image has-text-centered">
                                <img src="{% static 'images/landing/freeplan-img.png' %}"/>
                            </div>
                        </div>
                    </div>
                    <div class="column is-marginless">
                        <div class="card premium-card">
                            <div class="card-content">
                                <h3 class="is-size-4 has-text-centered has-text-weight-bold mb-3">
                                    Premium
                                </h3>
                                <ul class="has-text-black">
                                    <li class="list-item pb-2">Hasta 15 menús</li>
                                    <li class="list-item pb-2">Selección de temas</li>
                                    <li class="list-item pb-2">Posibilidad de añadir imágenes en los platos</li>
                                    <li class="list-item">Generación de código QR</li>
                                </ul>
                            </div>
                            <div class="card-image has-text-centered">
                                <img src="{% static 'images/landing/premiumplan-img.png' %}"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="has-text-white has-background-dark p-6 has-text-centered">
            <footer class="container is-flex is-justify-content-space-between is-align-items-center">
                <div class="left-footer is-flex is-flex-direction-column is-justify-content-center">
                    <span>Marcos Rodrigues © 2023</span>
                </div>
                <div class="right-footer is-flex is-flex-direction-row">
                    <a href="#" class="has-text-white">Términos de Servicio</a>
                    <a href="#" class="has-text-white">Política de Privacidad</a>
                </div>
            </footer>
        </div>
    </body>
</html>